export const data = [
    {
        id: 12345,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'P',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'P',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'98%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 12345,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'P',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'P',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'98%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 12345,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'P',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'P',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'98%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 12345,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'P',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'P',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'98%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 12345,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'A',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'A',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'90%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 12345,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'A',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'A',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'90%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 12345,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'A',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'A',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'90%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 12345,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'A',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'A',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'90%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 12345,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'A',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'A',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'90%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 12345,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'A',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'A',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'90%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 12345,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'A',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'A',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'90%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 12345,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'A',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'A',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'90%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 12345,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'A',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'A',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'90%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
    {
        id: 12345,
        name: 'Mahip',
        img: '../Assests/Images/profile.jpg',
        overroll: '98%',
        firstAttendance:'P',
        secondAttendance:'A',
        dailyAttendance:'P',
        weak:{
            mon:'P',
            Tue:'A',
            wed:'P',
            thu:'P',
            fri:'P',
            sat:'P',
            sun:'P',
        },
        month:{
            april:'98%',
            may:'98%',
            june:'98%',
            july:'98%',
            aug:'98%',
            sept:'90%',
            oct:'98%',
            nov:'98%',
            dec:'98%',
            jan:'98%',
            feb:'98%',
            mar:'98%',
        }
        
    },
]